#!/usr/bin/env node
/**
 * Incremental mutation testing — one source file at a time.
 *
 * A plain `stryker run` over `src/lib` is unusable here, and the reason is the
 * DRY RUN: before trying a single mutant, Stryker executes the whole test suite
 * once per runner process to learn which tests cover what. This suite is 2,638
 * tests, so that alone blew past Stryker's timeout and the run died having
 * measured nothing. Raising the timeout only converts a crash into a long wait.
 *
 * The fix is to stop making it read the whole suite. Each `src/lib/x.ts` has a
 * `tests/x.test.ts`, so this runs Stryker once per source file against ONLY the
 * matching test file: the dry run drops from minutes to about a second, and the
 * mutants that survive are the ones that file's own tests should have killed.
 *
 * Properties that matter, each learned the hard way:
 *  - **One file per process.** A crash costs that file, not the run.
 *  - **A hard per-file timeout.** Nothing hangs the batch.
 *  - **Results are written after EVERY file.** A batch interrupted halfway
 *    still leaves everything it measured — the earlier whole-directory attempts
 *    produced nothing at all when they died.
 *  - **Resumable.** Files already measured are skipped unless --force.
 *  - **The surviving mutants are kept, not just the score.** Stryker's json
 *    report lands in reports/mutation/files/<name>.json per file. A score of
 *    62% tells you nothing you can act on; the mutant list is the actual
 *    output, and the first full run produced only the score.
 *
 * Usage:
 *   node scripts/mutation-run.mjs                 # every lib file with a test
 *   node scripts/mutation-run.mjs richText merge  # just these
 *   node scripts/mutation-run.mjs --limit 10      # the next 10 unmeasured
 *   node scripts/mutation-run.mjs --report        # print what's been measured
 *   node scripts/mutation-run.mjs --survivors x   # print x's UNKILLED mutants
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync } from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const REPORT = path.join(ROOT, 'reports', 'mutation', 'summary.json')
/** Per-file mutant detail, written by Stryker's own json reporter. */
const detailPath = (base) => path.join(ROOT, 'reports', 'mutation', 'files', `${base}.json`)
/**
 * Generous on purpose: richText measured 1,995s (33 min) in the first full run,
 * which is ABOVE the 20 minutes this used to allow. A file that trips the
 * timeout is recorded as an error and loses its mutant detail, so the ceiling
 * has to sit clear of the worst real file rather than near it.
 */
const PER_FILE_TIMEOUT_MS = 60 * 60 * 1000

const argv = process.argv.slice(2)
const force = argv.includes('--force')
const reportOnly = argv.includes('--report')
const survivorsOnly = argv.includes('--survivors')
const limitIdx = argv.indexOf('--limit')
const limit = limitIdx >= 0 ? Number(argv[limitIdx + 1]) : Infinity
const names = argv.filter((a, i) => !a.startsWith('--') && !(limitIdx >= 0 && i === limitIdx + 1))

/** Every src/lib/*.ts that has a tests/<name>.test.ts beside it. */
function candidates() {
  return readdirSync(path.join(ROOT, 'src', 'lib'))
    .filter((f) => f.endsWith('.ts'))
    .map((f) => f.replace(/\.ts$/, ''))
    .filter((base) => existsSync(path.join(ROOT, 'tests', `${base}.test.ts`)))
    .sort()
}

const loadReport = () => {
  try { return JSON.parse(readFileSync(REPORT, 'utf8')) } catch { return { files: {} } }
}
const saveReport = (report) => {
  mkdirSync(path.dirname(REPORT), { recursive: true })
  writeFileSync(REPORT, JSON.stringify(report, null, 2) + '\n')
}

/**
 * Two generated configs per run, both deleted afterwards:
 *
 *  - a vitest config including ONLY this file's own test — what makes the dry
 *    run cheap, and what disables the coverage thresholds (a whole-suite
 *    property; a one-file run always falls short, exits non-zero, and Stryker
 *    reports that as "something went wrong in the initial test run");
 *  - a stryker config pointing at it, because `vitest.configFile` is a config
 *    key with no CLI equivalent.
 */
function writeScopedConfigs(base) {
  const vitestFile = path.join(ROOT, `vitest.mutation.${base}.config.ts`)
  writeFileSync(vitestFile, [
    "/// <reference types=\"vitest\" />",
    "import { defineConfig } from 'vite'",
    "import baseConfig from './vite.config'",
    '',
    '// Generated by scripts/mutation-run.mjs — safe to delete.',
    '//',
    "// Spread, NOT mergeConfig: mergeConfig CONCATENATES arrays, so `include`",
    '// became the base glob PLUS this one file and the dry run still discovered',
    '// all ~161 test files. That silently undid the whole point of the scoped',
    '// config — the run worked, it just took minutes per file instead of',
    '// seconds. Every other setting (plugins, environment, setupFiles,',
    '// testTimeout, maxWorkers) is inherited unchanged; only `include` and',
    '// `coverage` are replaced outright.',
    'export default defineConfig({',
    '  ...baseConfig,',
    '  test: {',
    '    ...baseConfig.test,',
    `    include: ['tests/${base}.test.ts'],`,
    '    // Replaces the base coverage block entirely, thresholds included: a',
    '    // one-file run can never meet whole-suite thresholds, and the non-zero',
    '    // exit reads as "something went wrong in the initial test run".',
    '    coverage: { enabled: false },',
    '  },',
    '})',
    '',
  ].join('\n'))

  const strykerFile = path.join(ROOT, `stryker.mutation.${base}.json`)
  writeFileSync(strykerFile, JSON.stringify({
    packageManager: 'npm',
    testRunner: 'vitest',
    vitest: { configFile: path.basename(vitestFile) },
    // The json report is the only record of WHICH mutants survived. Without it
    // a finished run leaves a score and nothing to act on — you know richText
    // is at 62% and not one thing to write a test about.
    reporters: ['clear-text', 'json'],
    jsonReporter: { fileName: `reports/mutation/files/${base}.json` },
    coverageAnalysis: 'perTest',
    mutate: [`src/lib/${base}.ts`],
    ignorePatterns: ['dist', 'release', 'coverage', 'reports', '.stryker-tmp'],
    concurrency: 2,
    timeoutMS: 60000,
    dryRunTimeoutMinutes: 5,
    thresholds: { high: 80, low: 60, break: null },
  }, null, 2) + '\n')

  return { vitestFile, strykerFile }
}

// Built with fromCharCode so the pattern holds no literal control character
// (which no-control-regex would flag, rightly, in hand-written source).
const ANSI = new RegExp(String.fromCharCode(27) + '\\[[0-9;]*m', 'g')
const stripAnsi = (s) => s.replace(ANSI, '')

/** Pull the score row out of Stryker's clear-text table. */
function parseScore(output) {
  const line = stripAnsi(output).split('\n').find((l) => /^\s*All files\s*\|/.test(l))
  if (!line) return null
  const c = line.split('|').map((x) => x.trim())
  const num = (i) => (c[i] === undefined || c[i] === '' ? null : Number(c[i]))
  return {
    score: num(1), scoreCovered: num(2), killed: num(3),
    timeout: num(4), survived: num(5), noCoverage: num(6), errors: num(7),
  }
}

function runOne(base) {
  const { vitestFile, strykerFile } = writeScopedConfigs(base)
  const started = Date.now()
  const secs = () => Math.round((Date.now() - started) / 1000)
  try {
    // Stryker's own entry via THIS node, not `npx`: spawning `npx.cmd` on
    // Windows fails with EINVAL unless a shell is used, and a shell would
    // reintroduce quoting problems on paths.
    const out = execFileSync(
      process.execPath,
      [path.join(ROOT, 'node_modules', '@stryker-mutator', 'core', 'bin', 'stryker.js'),
        'run', path.basename(strykerFile)],
      { cwd: ROOT, encoding: 'utf8', timeout: PER_FILE_TIMEOUT_MS, stdio: ['ignore', 'pipe', 'pipe'] },
    )
    const parsed = parseScore(out)
    return parsed ? { ...parsed, seconds: secs() } : { error: 'no score in output', seconds: secs() }
  } catch (e) {
    // A crash or a timeout costs this file and nothing else — that is the point.
    const text = stripAnsi(`${(e.stdout || '').toString()}\n${(e.stderr || '').toString()}`)
    const parsed = parseScore(text)
    if (parsed) return { ...parsed, seconds: secs() }
    const strykerErr = text.split('\n').find((l) => /ERROR|error:/i.test(l))
    const reason = e.killed || e.signal
      ? `timed out after ${PER_FILE_TIMEOUT_MS / 60000}m`
      : (strykerErr || (e.message || 'failed').split('\n')[0]).trim().slice(0, 200)
    return { error: reason, seconds: secs() }
  } finally {
    rmSync(vitestFile, { force: true })
    rmSync(strykerFile, { force: true })
  }
}

/**
 * Print the surviving (and uncovered) mutants for a measured file.
 *
 * This is the part you actually act on: each line is a change to the source
 * that every test still passed through, i.e. an assertion nobody wrote.
 */
function printSurvivors(base) {
  const file = detailPath(base)
  if (!existsSync(file)) {
    console.log(`\n${base}: no detail report — measured before the json reporter existed. `
      + `Re-run: node scripts/mutation-run.mjs --force ${base}`)
    return
  }
  let report
  try {
    report = JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    // A run killed mid-write leaves a truncated file; say so rather than throw
    // and take the other 73 files' output down with it.
    console.log(`\n${base}: detail report is unreadable — re-run with --force.`)
    return
  }
  for (const [name, entry] of Object.entries(report.files ?? {})) {
    const lines = String(entry.source ?? '').split('\n')
    const mutants = entry.mutants ?? []
    const open = mutants.filter((m) => m.status === 'Survived' || m.status === 'NoCoverage')
    console.log(`\n${name} — ${open.length} unkilled of ${mutants.length}`)
    for (const m of [...open].sort((a, b) => a.location.start.line - b.location.start.line)) {
      const src = (lines[m.location.start.line - 1] ?? '').trim()
      const to = String(m.replacement ?? '').replace(/\s+/g, ' ').slice(0, 60)
      console.log(`  L${String(m.location.start.line).padStart(4)} ${m.status === 'NoCoverage' ? 'uncov' : 'alive'} `
        + `${String(m.mutatorName).padEnd(22)} → ${to}\n         ${src.slice(0, 100)}`)
    }
    // A tally is the triage step: 200 StringLiteral mutants in one file is a
    // different problem (and often a deliberate non-problem) from 20 surviving
    // ConditionalExpression mutants, which are always missing assertions.
    const byMutator = {}
    for (const m of open) byMutator[m.mutatorName] = (byMutator[m.mutatorName] ?? 0) + 1
    const tally = Object.entries(byMutator).sort((a, b) => b[1] - a[1])
      .map(([k, n]) => `${k} ${n}`).join(', ')
    if (tally) console.log(`  — by mutator: ${tally}`)
  }
}

function summarise(report) {
  const measured = Object.entries(report.files).filter(([, v]) => !v.error)
  if (measured.length) {
    const sum = (k) => measured.reduce((n, [, v]) => n + (v[k] || 0), 0)
    const total = sum('killed') + sum('survived') + sum('noCoverage') + sum('timeout')
    console.log(`\nMeasured ${measured.length} file(s): ${sum('killed')}/${total} mutants killed `
      + `(${(100 * sum('killed') / Math.max(total, 1)).toFixed(1)}%).`)
    const weakest = measured
      .filter(([, v]) => typeof v.score === 'number')
      .sort((a, b) => a[1].score - b[1].score)
      .slice(0, 12)
    console.log('\nWeakest files — where assertions are missing:')
    for (const [name, v] of weakest) {
      console.log(`  ${String(v.score).padStart(6)}%  ${name.padEnd(24)} ${v.survived} survived, ${v.noCoverage} uncovered`)
    }
  }
  const failed = Object.entries(report.files).filter(([, v]) => v.error)
  if (failed.length) {
    console.log(`\n${failed.length} file(s) could not be measured:`)
    for (const [name, v] of failed) console.log(`  ${name}: ${v.error}`)
  }
  const stale = measured.filter(([name]) => !existsSync(detailPath(name))).map(([name]) => name)
  if (stale.length) {
    console.log(`\n${stale.length} file(s) have a score but no mutant detail (measured before the`
      + ` json reporter). A plain run re-measures them:\n  ${stale.join(' ')}`)
  }
}

function main() {
  const report = loadReport()
  if (reportOnly) { summarise(report); return }
  if (survivorsOnly) {
    const bases = names.length
      ? names
      : Object.keys(report.files).filter((b) => !report.files[b].error).sort()
    for (const b of bases) printSurvivors(b)
    return
  }

  let todo = names.length ? names : candidates()
  // "Measured" means a score AND the mutant detail that makes the score
  // actionable. A run from before the json reporter left only the former, and
  // skipping those would resume into a state you still can't act on.
  if (!force) {
    todo = todo.filter((b) => !report.files[b] || report.files[b].error || !existsSync(detailPath(b)))
  }
  todo = todo.slice(0, limit)

  if (!todo.length) {
    console.log('Nothing to do — everything is measured. --force to re-measure, --report to print,\n'
      + '--survivors [file…] to list the mutants no test killed.')
    return
  }
  console.log(`Measuring ${todo.length} file(s); results are saved after each one.\n`)

  for (const [i, base] of todo.entries()) {
    process.stdout.write(`[${i + 1}/${todo.length}] ${base} … `)
    const result = runOne(base)
    report.files[base] = { ...result, at: new Date().toISOString() }
    saveReport(report) // after EVERY file, so an interrupt keeps what it measured
    console.log(result.error
      ? `ERROR — ${result.error} [${result.seconds}s]`
      : `${result.score}% (${result.killed} killed, ${result.survived} survived, ${result.noCoverage} no-cov) [${result.seconds}s]`)
  }
  summarise(report)
}

main()
