#!/usr/bin/env node
/**
 * Incremental mutation testing — one source file at a time.
 *
 * A plain `stryker run` over `src/lib` is unusable here, and the reason is the
 * DRY RUN: before trying a single mutant, Stryker executes the whole test suite
 * once per runner process to learn which tests cover what. This suite is 2,638
 * tests, so that alone blew past Stryker's timeout and the run died having
 * measured nothing. Raising the timeout only converts a crash into a long wait.
 *
 * The fix is to stop making it read the whole suite. Each `src/lib/x.ts` has a
 * `tests/x.test.ts`, so this runs Stryker once per source file against ONLY the
 * matching test file: the dry run drops from minutes to about a second, and the
 * mutants that survive are the ones that file's own tests should have killed.
 *
 * Properties that matter, each learned the hard way:
 *  - **One file per process.** A crash costs that file, not the run.
 *  - **A hard per-file timeout.** Nothing hangs the batch.
 *  - **Results are written after EVERY file.** A batch interrupted halfway
 *    still leaves everything it measured — the earlier whole-directory attempts
 *    produced nothing at all when they died.
 *  - **Resumable.** Files already measured are skipped unless --force.
 *
 * Usage:
 *   node scripts/mutation-run.mjs                 # every lib file with a test
 *   node scripts/mutation-run.mjs richText merge  # just these
 *   node scripts/mutation-run.mjs --limit 10      # the next 10 unmeasured
 *   node scripts/mutation-run.mjs --report        # print what's been measured
 */
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'

const execFileAsync = promisify(execFile)
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync } from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const REPORT = path.join(ROOT, 'reports', 'mutation', 'summary.json')
/**
 * Two levels of parallelism, and the outer one is what makes this finish.
 *
 * Stryker's own `concurrency` only parallelises mutants WITHIN one file, and a
 * small file cannot saturate a 12-core machine — the first batch averaged one
 * file per 20 minutes with ten cores idle. Since each file is scoped to its own
 * test, files are independent, so several run at once: FILE_PARALLELISM files x
 * STRYKER_CONCURRENCY mutant workers each.
 */
const FILE_PARALLELISM = Number(process.env.MUTATION_FILES ?? 3)
const STRYKER_CONCURRENCY = Number(process.env.MUTATION_WORKERS ?? 2)
/**
 * Lower than it was. A file that cannot be measured in 10 minutes is telling
 * you something (usually that its own test file is slow); spending 20 minutes
 * to learn the same thing just costs the batch an extra ten. Timeouts are
 * recorded and retried on the next run, so nothing is lost by being impatient.
 */
const PER_FILE_TIMEOUT_MS = Number(process.env.MUTATION_TIMEOUT_MIN ?? 10) * 60 * 1000

const argv = process.argv.slice(2)
const force = argv.includes('--force')
const reportOnly = argv.includes('--report')
const limitIdx = argv.indexOf('--limit')
const limit = limitIdx >= 0 ? Number(argv[limitIdx + 1]) : Infinity
const names = argv.filter((a, i) => !a.startsWith('--') && !(limitIdx >= 0 && i === limitIdx + 1))

/** Every src/lib/*.ts that has a tests/<name>.test.ts beside it. */
function candidates() {
  return readdirSync(path.join(ROOT, 'src', 'lib'))
    .filter((f) => f.endsWith('.ts'))
    .map((f) => f.replace(/\.ts$/, ''))
    .filter((base) => existsSync(path.join(ROOT, 'tests', `${base}.test.ts`)))
    .sort()
}

const loadReport = () => {
  try { return JSON.parse(readFileSync(REPORT, 'utf8')) } catch { return { files: {} } }
}
const saveReport = (report) => {
  mkdirSync(path.dirname(REPORT), { recursive: true })
  writeFileSync(REPORT, JSON.stringify(report, null, 2) + '\n')
}

/**
 * Two generated configs per run, both deleted afterwards:
 *
 *  - a vitest config including ONLY this file's own test — what makes the dry
 *    run cheap, and what disables the coverage thresholds (a whole-suite
 *    property; a one-file run always falls short, exits non-zero, and Stryker
 *    reports that as "something went wrong in the initial test run");
 *  - a stryker config pointing at it, because `vitest.configFile` is a config
 *    key with no CLI equivalent.
 */
function writeScopedConfigs(base) {
  const vitestFile = path.join(ROOT, `vitest.mutation.${base}.config.ts`)
  writeFileSync(vitestFile, [
    "import { defineConfig, mergeConfig } from 'vite'",
    "import base from './vite.config'",
    '',
    '// Generated by scripts/mutation-run.mjs — safe to delete.',
    'export default mergeConfig(base, defineConfig({',
    '  test: {',
    `    include: ['tests/${base}.test.ts'],`,
    '    coverage: { enabled: false },',
    '  },',
    '}))',
    '',
  ].join('\n'))

  const strykerFile = path.join(ROOT, `stryker.mutation.${base}.json`)
  writeFileSync(strykerFile, JSON.stringify({
    packageManager: 'npm',
    testRunner: 'vitest',
    vitest: { configFile: path.basename(vitestFile) },
    reporters: ['clear-text'],
    coverageAnalysis: 'perTest',
    mutate: [`src/lib/${base}.ts`],
    // Its OWN sandbox. Stryker copies the project into a temp dir before
    // mutating it, and the default name is shared — so parallel runs deleted
    // each other's sandbox mid-flight and failed with
    // "ENOENT: no such file or directory, copyfile". This is what makes
    // file-level parallelism safe at all.
    tempDirName: `.stryker-tmp-${base}`,
    ignorePatterns: ['dist', 'release', 'coverage', 'reports', '.stryker-tmp*'],
    concurrency: STRYKER_CONCURRENCY,
    timeoutMS: 60000,
    dryRunTimeoutMinutes: 10,
    thresholds: { high: 80, low: 60, break: null },
  }, null, 2) + '\n')

  return { vitestFile, strykerFile }
}

// Built with fromCharCode so the pattern holds no literal control character
// (which no-control-regex would flag, rightly, in hand-written source).
const ANSI = new RegExp(String.fromCharCode(27) + '\\[[0-9;]*m', 'g')
const stripAnsi = (s) => s.replace(ANSI, '')

/** Pull the score row out of Stryker's clear-text table. */
function parseScore(output) {
  const line = stripAnsi(output).split('\n').find((l) => /^\s*All files\s*\|/.test(l))
  if (!line) return null
  const c = line.split('|').map((x) => x.trim())
  const num = (i) => (c[i] === undefined || c[i] === '' ? null : Number(c[i]))
  return {
    score: num(1), scoreCovered: num(2), killed: num(3),
    timeout: num(4), survived: num(5), noCoverage: num(6), errors: num(7),
  }
}

async function runOne(base) {
  const { vitestFile, strykerFile } = writeScopedConfigs(base)
  const started = Date.now()
  const secs = () => Math.round((Date.now() - started) / 1000)
  try {
    // Stryker's own entry via THIS node, not `npx`: spawning `npx.cmd` on
    // Windows fails with EINVAL unless a shell is used, and a shell would
    // reintroduce quoting problems on paths.
    const { stdout: out } = await execFileAsync(
      process.execPath,
      [path.join(ROOT, 'node_modules', '@stryker-mutator', 'core', 'bin', 'stryker.js'),
        'run', path.basename(strykerFile)],
      { cwd: ROOT, encoding: 'utf8', timeout: PER_FILE_TIMEOUT_MS, maxBuffer: 64 * 1024 * 1024 },
    )
    const parsed = parseScore(out)
    return parsed ? { ...parsed, seconds: secs() } : { error: 'no score in output', seconds: secs() }
  } catch (e) {
    // A crash or a timeout costs this file and nothing else — that is the point.
    const text = stripAnsi(`${(e.stdout || '').toString()}\n${(e.stderr || '').toString()}`)
    const parsed = parseScore(text)
    if (parsed) return { ...parsed, seconds: secs() }
    const strykerErr = text.split('\n').find((l) => /ERROR|error:/i.test(l))
    const reason = e.killed || e.signal
      ? `timed out after ${PER_FILE_TIMEOUT_MS / 60000}m`
      : (strykerErr || (e.message || 'failed').split('\n')[0]).trim().slice(0, 200)
    return { error: reason, seconds: secs() }
  } finally {
    rmSync(vitestFile, { force: true })
    rmSync(strykerFile, { force: true })
    rmSync(path.join(ROOT, `.stryker-tmp-${base}`), { recursive: true, force: true })
  }
}

function summarise(report) {
  const measured = Object.entries(report.files).filter(([, v]) => !v.error)
  if (measured.length) {
    const sum = (k) => measured.reduce((n, [, v]) => n + (v[k] || 0), 0)
    const total = sum('killed') + sum('survived') + sum('noCoverage') + sum('timeout')
    console.log(`\nMeasured ${measured.length} file(s): ${sum('killed')}/${total} mutants killed `
      + `(${(100 * sum('killed') / Math.max(total, 1)).toFixed(1)}%).`)
    const weakest = measured
      .filter(([, v]) => typeof v.score === 'number')
      .sort((a, b) => a[1].score - b[1].score)
      .slice(0, 12)
    console.log('\nWeakest files — where assertions are missing:')
    for (const [name, v] of weakest) {
      console.log(`  ${String(v.score).padStart(6)}%  ${name.padEnd(24)} ${v.survived} survived, ${v.noCoverage} uncovered`)
    }
  }
  const failed = Object.entries(report.files).filter(([, v]) => v.error)
  if (failed.length) {
    console.log(`\n${failed.length} file(s) could not be measured:`)
    for (const [name, v] of failed) console.log(`  ${name}: ${v.error}`)
  }
}

async function main() {
  const report = loadReport()
  if (reportOnly) { summarise(report); return }

  let todo = names.length ? names : candidates()
  if (!force) todo = todo.filter((b) => !report.files[b] || report.files[b].error)
  todo = todo.slice(0, limit)

  if (!todo.length) {
    console.log('Nothing to do — everything is measured. --force to re-measure, --report to print.')
    return
  }
  console.log(`Measuring ${todo.length} file(s), ${FILE_PARALLELISM} at a time; `
    + 'results are saved after each one.\n')

  // A worker pool over FILES. Stryker's own concurrency only parallelises
  // mutants within one file, which left ten of twelve cores idle and averaged
  // one file per 20 minutes. Files are independent here (each is scoped to its
  // own test), so they run several at a time.
  let next = 0
  let done = 0
  const worker = async () => {
    for (;;) {
      const i = next++
      if (i >= todo.length) return
      const base = todo[i]
      const result = await runOne(base)
      report.files[base] = { ...result, at: new Date().toISOString() }
      saveReport(report) // after EVERY file, so an interrupt keeps what it measured
      done++
      console.log(`[${String(done).padStart(3)}/${todo.length}] ${base.padEnd(24)} `
        + (result.error
          ? `ERROR — ${result.error} [${result.seconds}s]`
          : `${String(result.score).padStart(6)}% (${result.killed} killed, ${result.survived} survived, ${result.noCoverage} no-cov) [${result.seconds}s]`))
    }
  }
  await Promise.all(Array.from({ length: Math.min(FILE_PARALLELISM, todo.length) }, worker))

  summarise(report)
}

await main()
